import React, { useState } from 'react';
import { 
  Package, 
  CheckCircle2, 
  Clock, 
  Plus, 
  Search, 
  Filter, 
  Backpack, 
  Printer, 
  Trash2, 
  Tag, 
  Layers, 
  ShieldAlert,
  Building,
  Check
} from 'lucide-react';
import { MasterSupplyItem, StudentRequiredItem, TripProject } from '../types';
import { aggregateActivitySupplies } from '../utils/tripHelpers';

interface SuppliesViewProps {
  project: TripProject;
  onUpdateSupplies: (supplies: MasterSupplyItem[]) => void;
  onUpdateStudentItems: (items: StudentRequiredItem[]) => void;
  onPrintPackingSlip: () => void;
}

export const SuppliesView: React.FC<SuppliesViewProps> = ({
  project,
  onUpdateSupplies,
  onUpdateStudentItems,
  onPrintPackingSlip,
}) => {
  const [activeTab, setActiveTab] = useState<'master' | 'student'>('master');
  
  // Master Supplies Filters
  const [masterFilter, setMasterFilter] = useState<'all' | 'equipment' | 'supplies' | 'safety' | 'food'>('all');
  const [masterStatusFilter, setMasterStatusFilter] = useState<'all' | 'needed' | 'reserved' | 'packed'>('all');
  const [searchQuery, setSearchQuery] = useState('');

  // Add Master Item Form State
  const [isAddingMaster, setIsAddingMaster] = useState(false);
  const [newItemName, setNewItemName] = useState('');
  const [newItemCategory, setNewItemCategory] = useState<MasterSupplyItem['category']>('equipment');
  const [newItemQty, setNewItemQty] = useState(1);
  const [newItemUnit, setNewItemUnit] = useState('sets');
  const [newItemProvider, setNewItemProvider] = useState<MasterSupplyItem['providedBy']>('school');

  // Add Student Item Form State
  const [isAddingStudent, setIsAddingStudent] = useState(false);
  const [studentItemName, setStudentItemName] = useState('');
  const [studentCategory, setStudentCategory] = useState<StudentRequiredItem['category']>('clothing');
  const [studentIsMandatory, setStudentIsMandatory] = useState(true);
  const [studentNotes, setStudentNotes] = useState('');

  // Dynamic aggregation from placed activities + manual base supplies
  const allMasterItems = aggregateActivitySupplies(
    project.activities,
    project.days,
    project.supplies
  );

  // Status stats
  const totalMasterCount = allMasterItems.length;
  const packedMasterCount = allMasterItems.filter((i) => i.status === 'packed').length;
  const packedPercent = totalMasterCount > 0 ? Math.round((packedMasterCount / totalMasterCount) * 100) : 0;

  // Filtered Master Items
  const filteredMasterItems = allMasterItems.filter((item) => {
    const matchesCategory = masterFilter === 'all' || item.category === masterFilter;
    const matchesStatus = masterStatusFilter === 'all' || item.status === masterStatusFilter;
    const matchesSearch = item.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
      (item.activitySourceNames && item.activitySourceNames.some((s) => s.toLowerCase().includes(searchQuery.toLowerCase())));
    return matchesCategory && matchesStatus && matchesSearch;
  });

  const handleToggleStatus = (item: MasterSupplyItem) => {
    const nextStatus: Record<MasterSupplyItem['status'], MasterSupplyItem['status']> = {
      needed: 'reserved',
      reserved: 'packed',
      packed: 'needed',
    };
    const updated = allMasterItems.map((i) =>
      i.id === item.id ? { ...i, status: nextStatus[i.status] } : i
    );
    onUpdateSupplies(updated);
  };

  const handleCreateMasterItem = (e: React.FormEvent) => {
    e.preventDefault();
    if (!newItemName.trim()) return;

    const newItem: MasterSupplyItem = {
      id: `sup-${Date.now()}`,
      name: newItemName.trim(),
      category: newItemCategory,
      quantityNeeded: Number(newItemQty) || 1,
      unit: newItemUnit.trim() || 'pcs',
      providedBy: newItemProvider,
      status: 'needed',
      autoGeneratedFromActivity: false,
    };

    onUpdateSupplies([...project.supplies, newItem]);
    setNewItemName('');
    setNewItemQty(1);
    setIsAddingMaster(false);
  };

  const handleDeleteMasterItem = (id: string) => {
    onUpdateSupplies(project.supplies.filter((i) => i.id !== id));
  };

  const handleCreateStudentItem = (e: React.FormEvent) => {
    e.preventDefault();
    if (!studentItemName.trim()) return;

    const newItem: StudentRequiredItem = {
      id: `stud-${Date.now()}`,
      name: studentItemName.trim(),
      category: studentCategory,
      isRequired: studentIsMandatory,
      notes: studentNotes.trim() || undefined,
    };

    onUpdateStudentItems([...project.studentItems, newItem]);
    setStudentItemName('');
    setStudentNotes('');
    setIsAddingStudent(false);
  };

  const handleDeleteStudentItem = (id: string) => {
    onUpdateStudentItems(project.studentItems.filter((i) => i.id !== id));
  };

  const handleToggleStudentRequirement = (id: string) => {
    onUpdateStudentItems(
      project.studentItems.map((i) =>
        i.id === id ? { ...i, isRequired: !i.isRequired } : i
      )
    );
  };

  return (
    <div className="space-y-6">
      {/* Top Navigation Subtabs */}
      <div className="bg-amber-100/60 rounded-3xl border-2 border-amber-300/80 p-4 sm:p-5 shadow-sm">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-2xl bg-amber-700 text-amber-50 flex items-center justify-center font-bold shadow-xs">
              <Package className="w-6 h-6" />
            </div>
            <div>
              <h2 className="text-xl sm:text-2xl font-black font-display text-stone-900 tracking-tight">
                Gear & Supplies Manifest
              </h2>
              <p className="text-xs text-stone-600 font-medium">
                Aggregated activity gear, campsite provisions, and student packing requirements
              </p>
            </div>
          </div>

          {/* Subtab Buttons */}
          <div className="flex items-center gap-2 bg-amber-200/70 p-1 rounded-2xl border border-amber-300/80 self-start sm:self-auto">
            <button
              type="button"
              onClick={() => setActiveTab('master')}
              className={`px-4 py-2 rounded-xl text-xs font-black transition-all ${
                activeTab === 'master'
                  ? 'bg-amber-800 text-amber-50 shadow-xs'
                  : 'text-stone-700 hover:bg-amber-100'
              }`}
            >
              🏕️ Master Camp Gear ({allMasterItems.length})
            </button>
            <button
              type="button"
              onClick={() => setActiveTab('student')}
              className={`px-4 py-2 rounded-xl text-xs font-black transition-all ${
                activeTab === 'student'
                  ? 'bg-amber-800 text-amber-50 shadow-xs'
                  : 'text-stone-700 hover:bg-amber-100'
              }`}
            >
              🎒 Student Checklist ({project.studentItems.length})
            </button>
          </div>
        </div>

        {/* Progress Bar for Master Gear */}
        {activeTab === 'master' && (
          <div className="mt-4 pt-3 border-t border-amber-200/80">
            <div className="flex items-center justify-between text-xs font-bold text-stone-700 mb-1.5">
              <span>Overall Expedition Gear Readiness:</span>
              <span className="text-amber-900 font-black">{packedMasterCount} of {totalMasterCount} Ready ({packedPercent}%)</span>
            </div>
            <div className="w-full h-3 bg-amber-200/80 rounded-full overflow-hidden p-0.5 border border-amber-300">
              <div
                className="h-full bg-emerald-600 rounded-full transition-all duration-500 shadow-inner"
                style={{ width: `${packedPercent}%` }}
              />
            </div>
          </div>
        )}
      </div>

      {/* ===================== TAB 1: MASTER GEAR & SUPPLIES ===================== */}
      {activeTab === 'master' && (
        <div className="space-y-4">
          {/* Controls Bar: Search, Category, Status, Add button */}
          <div className="bg-white/90 rounded-2xl border-2 border-amber-200 p-4 shadow-xs flex flex-col md:flex-row gap-3 items-center justify-between">
            {/* Search */}
            <div className="relative w-full md:w-72">
              <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-stone-400" />
              <input
                type="text"
                placeholder="Search equipment, supplies..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-9 pr-3 py-1.5 rounded-xl bg-amber-50/50 border border-amber-300 text-xs font-semibold text-stone-800 outline-none focus:border-amber-600"
              />
            </div>

            {/* Category Filter Pills */}
            <div className="flex items-center gap-1 overflow-x-auto no-scrollbar w-full md:w-auto">
              {[
                { id: 'all', label: 'All Items' },
                { id: 'equipment', label: 'Hardware & Gear' },
                { id: 'supplies', label: 'Supplies' },
                { id: 'safety', label: 'Safety & First Aid' },
                { id: 'food', label: 'Food & Cooking' },
              ].map((f) => (
                <button
                  key={f.id}
                  type="button"
                  onClick={() => setMasterFilter(f.id as any)}
                  className={`px-3 py-1.5 rounded-xl text-xs font-bold whitespace-nowrap transition-colors border ${
                    masterFilter === f.id
                      ? 'bg-amber-700 text-white border-amber-800'
                      : 'bg-stone-50 text-stone-600 border-stone-200 hover:bg-amber-100/60'
                  }`}
                >
                  {f.label}
                </button>
              ))}
            </div>

            {/* Add Custom Item button */}
            <button
              id="add-master-gear-btn"
              type="button"
              onClick={() => setIsAddingMaster(!isAddingMaster)}
              className="w-full md:w-auto inline-flex items-center justify-center gap-1.5 px-4 py-2 rounded-xl text-xs font-black uppercase bg-amber-700 hover:bg-amber-800 text-white shadow-sm transition-all"
            >
              <Plus className="w-4 h-4" />
              <span>Add Custom Gear</span>
            </button>
          </div>

          {/* New Master Item Form Drawer */}
          {isAddingMaster && (
            <form
              onSubmit={handleCreateMasterItem}
              className="bg-amber-100/70 p-4 sm:p-5 rounded-2xl border-2 border-amber-300 space-y-4 animate-in fade-in"
            >
              <h3 className="text-sm font-black font-display text-amber-950 uppercase tracking-wider">
                Add Expedition Gear or Supply Item
              </h3>
              <div className="grid grid-cols-1 sm:grid-cols-4 gap-3">
                <div className="sm:col-span-2">
                  <label className="block text-[11px] font-bold text-stone-700 mb-1">Item Name</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. 5-Gallon Potable Water Jugs, Bear Spray..."
                    value={newItemName}
                    onChange={(e) => setNewItemName(e.target.value)}
                    className="w-full px-3 py-2 rounded-xl bg-white border border-amber-300 text-xs font-bold text-stone-800 outline-none focus:border-amber-600"
                  />
                </div>

                <div>
                  <label className="block text-[11px] font-bold text-stone-700 mb-1">Category</label>
                  <select
                    value={newItemCategory}
                    onChange={(e) => setNewItemCategory(e.target.value as any)}
                    className="w-full px-3 py-2 rounded-xl bg-white border border-amber-300 text-xs font-bold text-stone-800 outline-none"
                  >
                    <option value="equipment">Hardware & Gear</option>
                    <option value="supplies">Consumable Supplies</option>
                    <option value="safety">Safety & Medical</option>
                    <option value="food">Camp Cooking & Food</option>
                  </select>
                </div>

                <div>
                  <label className="block text-[11px] font-bold text-stone-700 mb-1">Provider Source</label>
                  <select
                    value={newItemProvider}
                    onChange={(e) => setNewItemProvider(e.target.value as any)}
                    className="w-full px-3 py-2 rounded-xl bg-white border border-amber-300 text-xs font-bold text-stone-800 outline-none"
                  >
                    <option value="school">School Shed</option>
                    <option value="camp_site">Camp Site Provided</option>
                    <option value="rent">Rental Company</option>
                    <option value="teacher">Teacher Brings</option>
                  </select>
                </div>
              </div>

              <div className="flex items-center justify-end gap-2">
                <button
                  type="button"
                  onClick={() => setIsAddingMaster(false)}
                  className="px-3 py-1.5 rounded-xl text-xs font-bold text-stone-600 hover:bg-amber-200 transition-colors"
                >
                  Cancel
                </button>
                <button
                  type="submit"
                  className="px-4 py-2 rounded-xl text-xs font-black uppercase bg-amber-700 hover:bg-amber-800 text-white shadow-xs transition-colors"
                >
                  Save Gear Item
                </button>
              </div>
            </form>
          )}

          {/* Master Supplies Table / List */}
          <div className="bg-white rounded-3xl border-2 border-amber-200 overflow-hidden shadow-xs">
            <div className="divide-y divide-amber-100">
              {filteredMasterItems.map((item) => {
                const statusStyles = {
                  needed: { label: 'To Acquire', bg: 'bg-red-50 text-red-700 border-red-200' },
                  reserved: { label: 'Reserved / Ready', bg: 'bg-amber-50 text-amber-700 border-amber-200' },
                  packed: { label: 'Packed & Staged', bg: 'bg-emerald-50 text-emerald-700 border-emerald-200' },
                }[item.status];

                return (
                  <div
                    key={item.id}
                    className="p-3.5 sm:p-4 hover:bg-amber-50/40 transition-colors flex flex-col sm:flex-row sm:items-center justify-between gap-3"
                  >
                    <div className="flex items-start gap-3">
                      {/* Interactive Status Checkbox */}
                      <button
                        type="button"
                        onClick={() => handleToggleStatus(item)}
                        title="Click to advance status: Needed -> Reserved -> Packed"
                        className={`w-6 h-6 rounded-lg border-2 flex items-center justify-center shrink-0 mt-0.5 transition-all ${
                          item.status === 'packed'
                            ? 'bg-emerald-600 border-emerald-600 text-white shadow-xs'
                            : item.status === 'reserved'
                            ? 'bg-amber-500 border-amber-500 text-white'
                            : 'bg-white border-stone-300 hover:border-amber-500'
                        }`}
                      >
                        {item.status === 'packed' && <Check className="w-4 h-4 stroke-[3]" />}
                        {item.status === 'reserved' && <Clock className="w-3.5 h-3.5" />}
                      </button>

                      <div>
                        <div className="flex items-center gap-2 flex-wrap">
                          <h4 className="text-sm font-extrabold text-stone-900 font-display">
                            {item.name}
                          </h4>
                          <span className={`text-[10px] font-black uppercase px-2 py-0.5 rounded-full border ${statusStyles.bg}`}>
                            {statusStyles.label}
                          </span>
                          {item.autoGeneratedFromActivity && (
                            <span className="text-[10px] font-bold px-2 py-0.5 rounded-full bg-stone-100 text-stone-600 border border-stone-200">
                              ⚡ From Activities
                            </span>
                          )}
                        </div>

                        {/* Activity sources info */}
                        {item.activitySourceNames && item.activitySourceNames.length > 0 && (
                          <p className="text-[11px] text-stone-500 mt-1 font-medium">
                            <span className="font-bold text-stone-700">Required by:</span>{' '}
                            {item.activitySourceNames.join(', ')}
                          </p>
                        )}
                      </div>
                    </div>

                    {/* Right side controls */}
                    <div className="flex items-center gap-2 self-end sm:self-center">
                      <button
                        type="button"
                        onClick={() => handleToggleStatus(item)}
                        className="text-xs font-bold px-3 py-1.5 rounded-xl border border-stone-200 hover:bg-amber-100/70 text-stone-700 transition-colors"
                      >
                        Advance Status
                      </button>

                      {!item.autoGeneratedFromActivity && (
                        <button
                          type="button"
                          onClick={() => handleDeleteMasterItem(item.id)}
                          className="p-1.5 text-stone-400 hover:text-red-700 hover:bg-red-50 rounded-lg transition-colors"
                        >
                          <Trash2 className="w-4 h-4" />
                        </button>
                      )}
                    </div>
                  </div>
                );
              })}

              {filteredMasterItems.length === 0 && (
                <div className="p-8 text-center text-stone-500 text-xs font-medium">
                  No gear or supplies match your filter.
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* ===================== TAB 2: STUDENT REQUIRED ITEMS ===================== */}
      {activeTab === 'student' && (
        <div className="space-y-4">
          {/* Student Header info & Print button */}
          <div className="bg-white/90 rounded-2xl border-2 border-amber-200 p-4 shadow-xs flex flex-col sm:flex-row gap-3 items-center justify-between">
            <div>
              <h3 className="text-sm font-black font-display text-stone-900 uppercase tracking-wider">
                Student & Parent Mandatory Packing List
              </h3>
              <p className="text-xs text-stone-500 font-medium">
                Items students must bring from home for the late October 2026 trip
              </p>
            </div>

            <div className="flex items-center gap-2 self-stretch sm:self-auto">
              <button
                type="button"
                onClick={onPrintPackingSlip}
                className="flex-1 sm:flex-none inline-flex items-center justify-center gap-1.5 px-3.5 py-2 rounded-xl text-xs font-bold bg-stone-100 hover:bg-stone-200 text-stone-800 border border-stone-300 shadow-xs transition-colors"
              >
                <Printer className="w-3.5 h-3.5" />
                <span>Print Student Slip</span>
              </button>

              <button
                id="add-student-item-btn"
                type="button"
                onClick={() => setIsAddingStudent(!isAddingStudent)}
                className="flex-1 sm:flex-none inline-flex items-center justify-center gap-1.5 px-4 py-2 rounded-xl text-xs font-black uppercase bg-amber-700 hover:bg-amber-800 text-white shadow-xs transition-colors"
              >
                <Plus className="w-4 h-4" />
                <span>Add Student Item</span>
              </button>
            </div>
          </div>

          {/* Add Student Item Drawer */}
          {isAddingStudent && (
            <form
              onSubmit={handleCreateStudentItem}
              className="bg-amber-100/70 p-4 sm:p-5 rounded-2xl border-2 border-amber-300 space-y-4 animate-in fade-in"
            >
              <h4 className="text-xs font-black font-display text-amber-950 uppercase tracking-wider">
                Define Required Student Equipment
              </h4>
              <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
                <div className="sm:col-span-2">
                  <label className="block text-[11px] font-bold text-stone-700 mb-1">Item Title</label>
                  <input
                    type="text"
                    required
                    placeholder="e.g. 3-Season Sleeping Bag (Rated 20°F – 30°F)..."
                    value={studentItemName}
                    onChange={(e) => setStudentItemName(e.target.value)}
                    className="w-full px-3 py-2 rounded-xl bg-white border border-amber-300 text-xs font-bold text-stone-800 outline-none focus:border-amber-600"
                  />
                </div>

                <div>
                  <label className="block text-[11px] font-bold text-stone-700 mb-1">Category</label>
                  <select
                    value={studentCategory}
                    onChange={(e) => setStudentCategory(e.target.value as any)}
                    className="w-full px-3 py-2 rounded-xl bg-white border border-amber-300 text-xs font-bold text-stone-800 outline-none"
                  >
                    <option value="clothing">Clothing & Layers</option>
                    <option value="bedding">Bedding & Sleep System</option>
                    <option value="footwear">Footwear</option>
                    <option value="safety">Safety & Flashlight</option>
                    <option value="toiletries">Toiletries & Hygiene</option>
                    <option value="extras">Extras & Gear</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-[11px] font-bold text-stone-700 mb-1">
                  Parent Guidance & Notes (e.g. Temperature specs, non-cotton rule)
                </label>
                <input
                  type="text"
                  placeholder="e.g. Nights drop to ~36°F in late October. Wool or synthetic recommended."
                  value={studentNotes}
                  onChange={(e) => setStudentNotes(e.target.value)}
                  className="w-full px-3 py-2 rounded-xl bg-white border border-amber-300 text-xs font-medium text-stone-800 outline-none focus:border-amber-600"
                />
              </div>

              <div className="flex items-center justify-between pt-1">
                <label className="flex items-center gap-2 text-xs font-bold text-stone-800 cursor-pointer">
                  <input
                    type="checkbox"
                    checked={studentIsMandatory}
                    onChange={(e) => setStudentIsMandatory(e.target.checked)}
                    className="w-4 h-4 rounded text-amber-600"
                  />
                  <span>Mandatory (Checked at pre-trip inspection)</span>
                </label>

                <div className="flex items-center gap-2">
                  <button
                    type="button"
                    onClick={() => setIsAddingStudent(false)}
                    className="px-3 py-1.5 rounded-xl text-xs font-bold text-stone-600 hover:bg-amber-200"
                  >
                    Cancel
                  </button>
                  <button
                    type="submit"
                    className="px-4 py-2 rounded-xl text-xs font-black uppercase bg-amber-700 text-white hover:bg-amber-800 shadow-xs"
                  >
                    Save Student Item
                  </button>
                </div>
              </div>
            </form>
          )}

          {/* Student Items List */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
            {project.studentItems.map((item) => (
              <div
                key={item.id}
                className="bg-white rounded-2xl border-2 border-amber-200 p-4 flex flex-col justify-between gap-2 shadow-xs hover:border-amber-400 transition-colors"
              >
                <div>
                  <div className="flex items-start justify-between gap-2">
                    <h4 className="text-sm font-black text-stone-900 font-display">
                      {item.name}
                    </h4>
                    <button
                      type="button"
                      onClick={() => handleToggleStudentRequirement(item.id)}
                      className={`text-[10px] font-black uppercase px-2.5 py-0.5 rounded-full border transition-all ${
                        item.isRequired
                          ? 'bg-red-100 text-red-800 border-red-300'
                          : 'bg-stone-100 text-stone-600 border-stone-200'
                      }`}
                    >
                      {item.isRequired ? 'Mandatory' : 'Optional'}
                    </button>
                  </div>

                  {item.notes && (
                    <p className="text-xs text-stone-600 mt-1.5 font-medium leading-relaxed">
                      💡 {item.notes}
                    </p>
                  )}
                </div>

                <div className="flex items-center justify-between pt-2 border-t border-amber-100 text-[11px] text-stone-500">
                  <span className="font-bold uppercase tracking-wider text-amber-900 bg-amber-100 px-2 py-0.5 rounded-md">
                    {item.category}
                  </span>
                  <button
                    type="button"
                    onClick={() => handleDeleteStudentItem(item.id)}
                    className="text-stone-400 hover:text-red-700 p-1"
                    title="Remove from student list"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
