import { ActivityCard, DayPlan, MasterSupplyItem, TeacherChaperone, TripProject } from '../types';

export interface TimelineSlot {
  activity: ActivityCard;
  stepNumber: number;
  startTime: string;
  endTime: string;
  isAfterSunset?: boolean;
}

/**
 * Adds minutes to an HH:mm 24-hour time string
 */
export function addMinutesToTime(timeStr: string, minutesToAdd: number): string {
  const [hStr, mStr] = timeStr.split(':');
  let hours = parseInt(hStr, 10);
  let minutes = parseInt(mStr, 10);

  if (isNaN(hours)) hours = 8;
  if (isNaN(minutes)) minutes = 0;

  const totalMin = hours * 60 + minutes + minutesToAdd;
  const newHours = Math.floor(totalMin / 60) % 24;
  const newMin = totalMin % 60;

  return `${String(newHours).padStart(2, '0')}:${String(newMin).padStart(2, '0')}`;
}

/**
 * Format 24-hour time to friendly 12-hour AM/PM string
 */
export function formatTime12h(timeStr: string): string {
  const [hStr, mStr] = timeStr.split(':');
  let hours = parseInt(hStr, 10);
  const minutes = mStr || '00';
  if (isNaN(hours)) return timeStr;
  const ampm = hours >= 12 ? 'PM' : 'AM';
  hours = hours % 12;
  if (hours === 0) hours = 12;
  return `${hours}:${minutes} ${ampm}`;
}

/**
 * Calculate timeline slots with 15-minute buffer transitions
 */
export function computeTimelineSlots(
  day: DayPlan,
  activities: ActivityCard[],
  transitionMinutes: number = 15
): TimelineSlot[] {
  const slots: TimelineSlot[] = [];
  let currentTime = day.startTime || '08:00';

  day.activityIds.forEach((actId, index) => {
    const act = activities.find((a) => a.id === actId);
    if (!act) return;

    const start = currentTime;
    const end = addMinutesToTime(start, act.durationMinutes);

    // In late October, sunset is around 18:15 (6:15 PM)
    const [endH] = end.split(':').map(Number);
    const isAfterSunset = endH >= 18;

    slots.push({
      activity: act,
      stepNumber: index + 1,
      startTime: start,
      endTime: end,
      isAfterSunset,
    });

    currentTime = addMinutesToTime(end, transitionMinutes);
  });

  return slots;
}

/**
 * Aggregates equipment and supplies from all active activities into a clean master list
 */
export function aggregateActivitySupplies(
  activities: ActivityCard[],
  activeDayPlans: DayPlan[],
  manualSupplies: MasterSupplyItem[]
): MasterSupplyItem[] {
  // Find which activities are placed on at least one day's timeline
  const activeActivityIds = new Set<string>();
  activeDayPlans.forEach((d) => d.activityIds.forEach((id) => activeActivityIds.add(id)));

  const equipmentMap = new Map<string, { count: number; sources: string[] }>();
  const suppliesMap = new Map<string, { count: number; sources: string[] }>();

  activities.forEach((act) => {
    // Only aggregate if placed on timeline (or all activities if none placed)
    const isScheduled = activeActivityIds.size === 0 || activeActivityIds.has(act.id);
    if (!isScheduled) return;

    act.requiredEquipment.forEach((eq) => {
      const clean = eq.trim();
      if (!clean) return;
      const existing = equipmentMap.get(clean) || { count: 0, sources: [] };
      existing.count += 1;
      if (!existing.sources.includes(act.name)) existing.sources.push(act.name);
      equipmentMap.set(clean, existing);
    });

    act.requiredSupplies.forEach((sup) => {
      const clean = sup.trim();
      if (!clean) return;
      const existing = suppliesMap.get(clean) || { count: 0, sources: [] };
      existing.count += 1;
      if (!existing.sources.includes(act.name)) existing.sources.push(act.name);
      suppliesMap.set(clean, existing);
    });
  });

  const generatedItems: MasterSupplyItem[] = [];

  equipmentMap.forEach((data, name) => {
    generatedItems.push({
      id: `auto-eq-${name.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
      name,
      category: 'equipment',
      quantityNeeded: 1,
      unit: 'set',
      providedBy: 'school',
      status: 'reserved',
      autoGeneratedFromActivity: true,
      activitySourceNames: data.sources,
    });
  });

  suppliesMap.forEach((data, name) => {
    generatedItems.push({
      id: `auto-sup-${name.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
      name,
      category: 'supplies',
      quantityNeeded: 1,
      unit: 'pack',
      providedBy: 'school',
      status: 'needed',
      autoGeneratedFromActivity: true,
      activitySourceNames: data.sources,
    });
  });

  // Combine manual base supplies with non-duplicate generated ones
  const finalItems: MasterSupplyItem[] = [...manualSupplies];

  generatedItems.forEach((gen) => {
    const existingIndex = finalItems.findIndex(
      (m) => m.name.toLowerCase() === gen.name.toLowerCase()
    );
    if (existingIndex >= 0) {
      // update sources
      finalItems[existingIndex] = {
        ...finalItems[existingIndex],
        activitySourceNames: Array.from(
          new Set([...(finalItems[existingIndex].activitySourceNames || []), ...(gen.activitySourceNames || [])])
        ),
      };
    } else {
      finalItems.push(gen);
    }
  });

  return finalItems;
}

/**
 * Generate Shareable URL hash
 */
export function encodeProjectToUrlHash(project: TripProject): string {
  try {
    const json = JSON.stringify(project);
    const encoded = encodeURIComponent(json);
    return `#plan=${encoded}`;
  } catch (err) {
    console.error('Failed to encode project state', err);
    return '';
  }
}

/**
 * Load project from URL hash if present
 */
export function decodeProjectFromUrlHash(): TripProject | null {
  try {
    const hash = window.location.hash;
    if (hash && hash.startsWith('#plan=')) {
      const jsonStr = decodeURIComponent(hash.replace('#plan=', ''));
      const parsed = JSON.parse(jsonStr) as TripProject;
      if (parsed && parsed.tripName && Array.isArray(parsed.days)) {
        return parsed;
      }
    }
  } catch (err) {
    console.warn('Could not decode project from URL hash', err);
  }
  return null;
}

/**
 * Export project as a downloadable .json file
 */
export function downloadProjectJson(project: TripProject) {
  const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(project, null, 2));
  const downloadAnchor = document.createElement('a');
  downloadAnchor.setAttribute('href', dataStr);
  const safeName = project.tripName.toLowerCase().replace(/[^a-z0-9]/g, '-');
  downloadAnchor.setAttribute('download', `${safeName}-plan.json`);
  document.body.appendChild(downloadAnchor);
  downloadAnchor.click();
  downloadAnchor.remove();
}

/**
 * Flow and safety analysis for a day
 */
export function analyzeDayFlow(day: DayPlan, activities: ActivityCard[]) {
  const slots = computeTimelineSlots(day, activities);
  const totalMinutes = slots.reduce((sum, s) => sum + s.activity.durationMinutes, 0);
  const highEnergyCount = slots.filter((s) => s.activity.energyLevel === 'high').length;
  const unassignedCount = slots.filter((s) => !s.activity.leadTeacherId).length;
  const afterSunsetCount = slots.filter((s) => s.isAfterSunset).length;

  const warnings: string[] = [];
  if (unassignedCount > 0) {
    warnings.push(`${unassignedCount} activity without a lead teacher supervisor assigned`);
  }
  if (highEnergyCount >= 3) {
    warnings.push('3+ high-energy challenges in one day; consider inserting a rest or meal break');
  }
  if (afterSunsetCount > 0) {
    warnings.push(`${afterSunsetCount} activity runs after October dusk (~6:15 PM); ensure lanterns/headlamps are ready`);
  }

  return {
    totalSlots: slots.length,
    totalMinutes,
    totalHours: (totalMinutes / 60).toFixed(1),
    highEnergyCount,
    unassignedCount,
    warnings,
  };
}
