export type ActivityCategory = 
  | 'hike' 
  | 'water' 
  | 'campcraft' 
  | 'teamwork' 
  | 'meal' 
  | 'campfire' 
  | 'rest';

export type EnergyLevel = 'low' | 'medium' | 'high';

export interface ActivityCard {
  id: string;
  name: string;
  description?: string;
  durationMinutes: number; // e.g. 45, 60, 90
  category: ActivityCategory;
  energyLevel: EnergyLevel;
  requiredEquipment: string[]; // e.g. ["Tents", "Compass", "Ropes"]
  requiredSupplies: string[];  // e.g. ["Firewood", "Marshmallows", "Matches"]
  leadTeacherId?: string;
  assistantTeacherIds?: string[];
  notes?: string;
  studentItemNeeded?: string; // e.g. "Hiking boots + Daypack"
  weatherDependent?: boolean;
  assignedGroup?: 'all' | 'group-1' | 'group-2'; // Group 1, Group 2, or shared (both groups)
  // Geolocation properties
  locationName?: string;
  coordinates?: {
    lat: number;
    lng: number;
  };
  // Desk canvas position & rotation (like desk.html)
  deskPosition?: {
    x: number;
    y: number;
    rotation?: number;
  };
}

export interface DayPlan {
  id: string;
  dayNumber: number;
  dateStr: string; // "2026-10-28"
  title: string;
  subtitle: string;
  startTime: string; // "08:00"
  activityIds: string[]; // ordered sequence of activity card IDs placed on this day's trail
}

export interface MasterSupplyItem {
  id: string;
  name: string;
  category: 'equipment' | 'supplies' | 'food' | 'safety' | 'campcraft';
  quantityNeeded: number;
  unit: string; // "pcs", "sets", "bags", "boxes", "kits"
  providedBy: 'school' | 'camp_site' | 'rent' | 'teacher';
  status: 'needed' | 'reserved' | 'packed';
  notes?: string;
  autoGeneratedFromActivity?: boolean;
  activitySourceNames?: string[];
}

export interface StudentRequiredItem {
  id: string;
  name: string;
  category: 'clothing' | 'bedding' | 'footwear' | 'safety' | 'toiletries' | 'extras';
  isRequired: boolean; // true = Mandatory, false = Optional/Recommended
  notes?: string;
  packedByStudentSampleCount?: number;
}

export interface TeacherChaperone {
  id: string;
  name: string;
  role: string; // e.g. "Science Teacher / Trip Director"
  phone: string;
  email: string;
  certifications: string[]; // e.g. ["Wilderness First Aid", "CPR", "Lifeguard", "Leave No Trace"]
  isLeadCoordinator?: boolean;
  notes?: string;
}

export interface ProjectMilestone {
  id: string;
  title: string;
  dueDate: string; // "2026-09-15"
  category: 'approval' | 'parents' | 'logistics' | 'safety' | 'payment';
  completed: boolean;
  assignedTo?: string;
  description?: string;
}

export interface StudentGroup {
  id: string; // 'group-1' | 'group-2'
  name: string; // e.g. "Group 1 - Alpha Wave"
  badgeColor: 'emerald' | 'amber' | 'blue' | 'indigo' | 'rose' | 'teal';
  arrivalDate: string; // "2026-10-28"
  arrivalTime: string; // "08:30"
  departureDate: string; // "2026-10-30"
  departureTime: string; // "13:00"
  leadTeacherId?: string;
  notes?: string; // Staggered arrival notes & overlap details
}

export interface StudentProfile {
  id: string;
  name: string;
  groupId: string; // 'group-1' | 'group-2'
  grade?: string; // "8th Grade" or "4sA", "6sB", etc.
  house?: string; // e.g. "centaurs", "pegasus", "titans", "unicorns"
  firebaseStudentId?: string;
  allergies?: string; // e.g. "Severe Peanut Allergy (Carries EpiPen)", "Bee stings"
  medicalRequirements?: string; // e.g. "Asthma inhaler before physical treks"
  dietaryRequirements?: string; // e.g. "Vegetarian", "Lactose intolerant"
  emergencyContactName?: string;
  emergencyContactPhone?: string;
  observations?: string; // Teacher/staff observations, tent pairings, water comfort
  medicalClearanceReceived: boolean;
  parentConsentReceived: boolean;
}

export interface TripProject {
  id: string;
  tripName: string;
  destination: string;
  baseLocation?: {
    name: string;
    lat: number;
    lng: number;
    zoom?: number;
  };
  startDate: string; // "2026-10-28"
  endDate: string;   // "2026-10-30"
  expectedStudents: number;
  days: DayPlan[];
  activities: ActivityCard[];
  supplies: MasterSupplyItem[];
  studentItems: StudentRequiredItem[];
  teachers: TeacherChaperone[];
  milestones: ProjectMilestone[];
  studentGroups: StudentGroup[];
  students: StudentProfile[];
  selectedPawn?: string;
  lastSavedAt: string;
}
